spring:
  application:
    name: multi-file
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/multi-db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /api/v1/
  port: 9192
